DELIMITER //
DROP PROCEDURE IF EXISTS RegistrarEstudianteComoAdministrador;
CREATE PROCEDURE RegistrarEstudianteComoAdministrador(
    IN DNI VARCHAR(255),
    IN AP_PATERNO VARCHAR(255),
    IN AP_MATERNO VARCHAR(255),
    IN NOMBRES VARCHAR(255),
    IN CELULAR_EST VARCHAR(9),
    IN CORREO VARCHAR(255),
    IN PASSWORD VARCHAR(255),
    IN SEXO VARCHAR(2),
    IN FECHA_NACIMIENTO VARCHAR(255),
    IN LUGAR_RESIDENCIA VARCHAR(8),
    IN DIRECCION VARCHAR(255),
    IN DISCAPACIDAD VARCHAR(4),
    IN TIPO_DISCAPACIDAD VARCHAR(4),
    IN ETNICA VARCHAR(4),
    IN TELEFONO VARCHAR(10),
    IN RUTA_FOTO VARCHAR(100),
    IN NOMBRE_COLEGIO VARCHAR(150),
    IN TIPO_COLEGIO VARCHAR(2),
    IN NOMBRE_COMPLETO_APO VARCHAR(200),
    IN CELULAR_APO VARCHAR(9),
    IN DNI_APO VARCHAR(8),
    IN COD_CARRERA VARCHAR(10), 
    IN PROCESO VARCHAR(4),
    IN SEDE_EXAM VARCHAR(20),
    IN PAGO_1 VARCHAR(20),
    IN PAGO_2 VARCHAR(20),
    IN PREPARATORIA VARCHAR(3),
    IN ID_AULA VARCHAR(20),
    IN YEAR_CONCLU VARCHAR(8)
)
BEGIN
	DECLARE usuario_existente INT;
    DECLARE datos_complementarios_existente INT;
    DECLARE estudiante_inscrito INT;
    -- Insertar datos en la tabla registros
    SELECT COUNT(*) INTO usuario_existente FROM registros WHERE registros.DNI = DNI;
	IF usuario_existente = 0 THEN
		INSERT INTO registros (TIPO_DOC, DNI, AP_PATERNO, AP_MATERNO, NOMBRES, CELULAR, CORREO, PASSWORD)
			VALUES ('DNI', DNI, AP_PATERNO, AP_MATERNO, NOMBRES, CELULAR_EST, CORREO, PASSWORD);
	ELSE
        SIGNAL SQLSTATE '01000' SET MESSAGE_TEXT = 'Usuario con DNI existente en registro';
	END IF;

    -- Obtener el ID del último registro insertado en registros
    SELECT COUNT(*) INTO datos_complementarios_existente FROM dat_complementarios WHERE dat_complementarios.DNI = DNI;
	IF datos_complementarios_existente = 0 THEN
    -- Insertar datos en la tabla dat_complementarios
		INSERT INTO dat_complementarios (DNI, SEXO, FECHA_NACIMIENTO, LUGAR_RESIDENCIA, DIRECCION, DISCAPACIDAD, TIPO_DISCAPACIDAD, ETNICA, TELEFONO, RUTA_FOTO, NOMBRE_COLEGIO, TIPO_COLEGIO, NOMBRE_COMPLETO_APO, CELULAR_APO, DNI_APO)
			VALUES (DNI, SEXO, FECHA_NACIMIENTO, LUGAR_RESIDENCIA, DIRECCION, DISCAPACIDAD, TIPO_DISCAPACIDAD, ETNICA, TELEFONO, RUTA_FOTO, NOMBRE_COLEGIO, TIPO_COLEGIO, NOMBRE_COMPLETO_APO, CELULAR_APO, DNI_APO);
	ELSE
        SIGNAL SQLSTATE '01000' SET MESSAGE_TEXT = 'El usuario ya cuenta con datos complementarios';
    END IF;
	
	SELECT COUNT(*) INTO estudiante_inscrito FROM inscritos WHERE inscritos.DNI = DNI AND inscritos.PROCESO = PROCESO;
	IF estudiante_inscrito = 0 THEN
    -- Insertar datos en la tabla inscritos
    INSERT INTO inscritos (DNI, COD_CARRERA, PROCESO, SEDE_EXAM, PAGO_1, PAGO_2, PREPARATORIA, ID_AULA, YEAR_CONCLU)
        VALUES (DNI, COD_CARRERA, PROCESO, SEDE_EXAM, PAGO_1, PAGO_2, PREPARATORIA, ID_AULA, YEAR_CONCLU);
	ELSE
        SIGNAL SQLSTATE '01000' SET MESSAGE_TEXT = 'El estudiante ya esta inscrito en el proceso que indico';
    END IF;
END //

DELIMITER ;
