export interface ResultadoInterface {
  id?: any,
  PROCESO?: any,
  SUBPROCESO?: any,
  CODIGO?: any,
  COD_FICHA?: any,
  COD_FICHA2?: any,
  POSTULANTE?: any,
  COD_P_OPCION?: any,
  P_OPCION?: any,
  COD_S_OPCION?: any,
  S_OPCION?: any,
  PUNT_1?: any,
  PUNT_2?: any,
  PUNT_T?: any,
  EST_1OPCION?: any,
  EST_2OPCION?: any,
  ASISTENCIA1?: any,
  ASISTENCIA2?: any,
  OPC_ING?: any,
  ORD_M1OP?: any,
  ORD_M2OP?: any,
  AULA1?: any,
  AULA2?: any,
  SEDE?: any,
  CONVENIO?: any,
}