export interface EstudianteCompleto  {
    DNI?: string,
    AP_PATERNO?: string,
    AP_MATERNO?: string,
    NOMBRES?: string,
    CELULAR_EST?: string,
    CELULAR?: string,
    ID_TIPO_MODALIDAD?: string,
    CORREO?: string,
    PASSWORD?: string,
    SEXO?: string,
    FECHA_NACIMIENTO?: string,
    LUGAR_RESIDENCIA?: string,
    DIRECCION?: string,
    DISCAPACIDAD?: string,
    TIPO_DISCAPACIDAD?: string,
    ETNICA?: string,
    TELEFONO?: string,
    RUTA_FOTO?: string,
    NOMBRE_COLEGIO?: string,
    TIPO_COLEGIO?: string,
    NOMBRE_COMPLETO_APO?: string,
    CELULAR_APO?: string,
    DNI_APO?: string,
    COD_CARRERA?: string,
    PROCESO?: string,
    SEDE_EXAM?: string,
    PAGO_1?: string,
    PAGO_2?: string,
    PREPARATORIA?: string,
    ID_AULA?: string,
    YEAR_CONCLU?: string,

}



